version: '3.9'
services:

  postgres:
    container_name: golangpg
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  redis:
    container_name: golangredis
    image: redis:alpine
    command: --port 6385
    ports:
      - 6385:6385

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: museum_app
    environment:
      PG_URL: postgres://user:pass@postgres:5432/postgres
    ports:
      - 3000:8080
    expose:
      - "3000"
    depends_on:
      - postgres

volumes:
  pg-data:
