app:
  name: go-clean-template
  version: 1.0.0

http:
  host: 0.0.0.0
  port: 8080
  jwt_secret_key: my-very-secret
  jwt_separate_key: AuthBearMuseum

logger:
  log_level: debug
  rollbar_env: go-clean-template

postgres:
  pool_max: 2
  url: "postgres://user:pass@localhost:5432/postgres"

redis:
  url: ""

env:
  level: development

s3:
  bucket_name: "594c4f91-17859372-8f32-4427-a9a9-fe3e172a48d1"
  end_point: "https://s3.timeweb.cloud"
  region: "ru-1"
  access_key: "access_key"
  secret_access_key: "secret_access_key"
