name: build-deploy

on:
  push:
    branches: main

jobs:
  use-build:
    uses: IGO-enviroment/backend_for_museum/.github/workflows/build.yml@main

  deploy:
    needs: use-build

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v2
        with:
          # the same name as used in the build workflow
          name: build-artifact
          # where to save the artifact
          # using the same path as in the build workflow "restores" the state from the end of the build workflow
          path: bin

      - name: Copy-Build-Golang-App
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          port: '${{ secrets.VM_SSH_PORT }}'
          password: '${{ secrets.VM_SSH_PASS }}'
          source: bin/
          target: /project/bin

      - name: Deploy-Build-Golang-App-To-Ubuntu-VM
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          port: '${{ secrets.VM_SSH_PORT }}'
          password: '${{ secrets.VM_SSH_PASS }}'
          script: |
            sudo systemctl restart museum-server
            sudo systemctl status museum-server 