name: Museum-Workflow
  on:
    push:
      branches:
        - main
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - run: go version

      - name: Install-Golang-Dependencies
        run: go mod download

      - name: Build-Golang-App
        run: GOOS=linux GOARCH=amd64 go build -o bin/linux_bin

      - name: Create-Env-File
        run: 'echo "APIKey=${{ secrets.APIKey }}" > bin/.env'

      # - name: Run-Unit-Test-Golang-App
      #  run: go test

      - name: Copy-Build-Golang-App
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          port: '${{ secrets.VM_SSH_PORT }}'
          source: bin/
          target: /project/bin

      - name: Deploy-Build-Golang-App-To-Ubuntu-VM
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          port: '${{ secrets.VM_SSH_PORT }}'
          script: |
            sudo systemctl restart museum-server
            sudo systemctl status museum-server 
